# Generated by Django 5.0.4 on 2024-04-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='position',
            field=models.IntegerField(default='1', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmarkcategory',
            name='position',
            field=models.IntegerField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
