# Generated by Django 5.0.4 on 2024-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_position_bookmarkcategory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookmarkcategory',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
