# Generated by Django 5.0.4 on 2024-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='bookmarkcategory',
            options={'ordering': ['position'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
