# Generated by Django 5.1.5 on 2025-01-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkcategory',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
