# Generated by Django 5.0.4 on 2024-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='url',
            field=models.URLField(default='https://example.com', unique=True),
            preserve_default=False,
        ),
    ]
