# Generated by Django 5.0.4 on 2024-05-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['position']},
        ),
    ]
