# Generated by Django 5.0.6 on 2024-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
