# Generated by Django 5.1.4 on 2025-01-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
