exclude: .*migrations\/.*
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.3.7
  hooks:
    - id: ruff

- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.31.1
  hooks:
    - id: djlint-django
