"""empty message

Revision ID: 8382b68cadfc
Revises: 
Create Date: 2024-04-06 14:55:08.827022

"""
import json
from alembic import op
import sqlalchemy as sa
from pathlib import Path


# revision identifiers, used by Alembic.
revision = '8382b68cadfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('theme',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('name', sa.String(), nullable=False),
                            sa.Column('background', sa.String(), nullable=False),
                            sa.Column('primary', sa.String(), nullable=False),
                            sa.Column('accent', sa.String(), nullable=False),
                            sa.Column('is_custom', sa.Boolean(), nullable=False),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    themes_src = Path(__file__).parent.parent.parent.resolve() / "app" / "themes" / "themes.json"
    with themes_src.open() as source:
        payload = source.read()
        op.bulk_insert(table, json.loads(payload))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme')
    # ### end Alembic commands ###
