"""Application desc and pinning

Revision ID: b88cbc4dfd6e
Revises: 0e384ae604ed
Create Date: 2024-04-07 18:29:50.807686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88cbc4dfd6e'
down_revision = '0e384ae604ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
